version: '3.8'

services:
  backend-test:
    build:
      context: ./backend
    env_file:
      - ./backend/.env.test
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./backend:/app
      - /app/node_modules
    command: npm test
